- type: !PartialOnly job
  id: ChiefMedicalOfficer
  requirements: !Clear
  - !type:RoleTimeRequirement
    role: JobChemist
    time: 7h
  - !type:RoleTimeRequirement
    role: JobMedicalDoctor
    time: 7h
  - !type:DepartmentTimeRequirement
    department: Medical
    time: 20h
  - !type:TraitsRequirement
    traits:
    - Iterator
    - Muted
    inverted: true
  access:
  - !Index:7 Surgery
  - !Index:7 Paramedic
  - !Index:7 Debrief
  - !Index:7 Shuttle
  canBeAntag: !Remove

- type: !PartialOnly startingGear
  id: CMOGear
  equipment:
    belt: ClothingBeltMedicalFilled # adding back belts
