- type: !PartialOnly job
  id: ResearchAssistant
  weight: -1
  canBeAntag: !Remove

- type: !PartialOnly startingGear
  id: ResearchAssistantGear
  equipment:
    belt: ClothingBeltStorageWaistbagScience
    shoes: !Remove
