- type: !PartialOnly antag
  id: HeadRev
  requirements: !Clear
  - !type:OverallPlaytimeRequirement
    time: 72h
  - !type:RoleTimeRequirement
    role: JobSecurityOfficer # Less important than some of the other antags to know
    time: 1h
  - !type:DepartmentTimeRequirement
    department: Command
    time: 12h # Have to be a leader. You're essentially making your own chain of command in this role
  playTimeTracker: AntagHeadRev

- type: !PartialOnly antag
  id: Rev
  playTimeTracker: AntagRev

- type: !PartialOnly startingGear
  id: HeadRevGear
  storage:
    back:
    - !Index:2 USSPUplinkImplanter
